name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 3.91.31.68
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "build/*"
          target: "/home/ubuntu/build"

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 3.91.31.68
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/build/* /var/www/html/
            sudo systemctl restart nginx